---
name: Build Rust SDK

on:
  push:
    branches:
      - main
    paths:
      - "src/rust/sdk/**"
      - "src/rust/types/**"
      - src/rust/Cargo.toml
      - src/rust/Cargo.lock
      - .github/workflows/build-rust-sdk.yml

  pull_request:
    branches:
      - main
    paths:
      - "src/rust/sdk/**"
      - "src/rust/types/**"
      - src/rust/Cargo.toml
      - src/rust/Cargo.lock
      - .github/workflows/build-rust-sdk.yml

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Setup mold
        uses: rui314/setup-mold@v1

      - name: Build Rust SDK
        run: cargo build --all-features
        working-directory: src/rust/sdk
        env:
          RUSTFLAGS: -C link-arg=-fuse-ld=mold
